resources:
  repositories:
    - repository: 'synopsys-azure-templates'
      type: 'git'
      name: 'synopsys-azure-templates'


pool:
      vmImage: 'ubuntu-latest'

jobs:
  - job: Build

    steps:
    - task: Maven@3
      displayName: 'Maven pom.xml'
      inputs:
        options: '-DskipITs -DskipTests --settings ./maven/settings.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
    
#    - task: SynopsysDetectTaskDev@7
#      inputs:
#        BlackDuckService: 'poc39-rhaines'
#        DetectVersion: 'latest'

  - template: 'coverity-auto-capture-self-hosted.yml@synopsys-azure-templates'
